# Generated by Django 4.2 on 2024-10-06 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cantidad_horas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.PositiveIntegerField()),
                ('nota_curso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('curso_alumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.curso')),
            ],
        ),
    ]
